name = "DocThemePC2"
uuid = "891028e3-bd96-440d-a0ed-4cea5ae68e00"
authors = ["Carsten Bauer <carsten.bauer@uni-paderborn.de> and contributors"]
version = "0.1.1"

[deps]
DocumenterTools = "35a29f4d-8980-5a13-9543-d66fff28ecb8"

[compat]
julia = "1.6"
DocumenterTools = "0.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
